# Generated by Django 5.2.6 on 2025-09-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_author_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
